services:
  proxy:
    image: nginx:alpine
    ports:
      - "80:80"
    networks:
      - devnet
    volumes:
      - ./nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend

  # TODO: Build first and then deploy
  # frontend:
  #   build: ./frontend
  #   command: ["npm", "run", "dev"]
  #   networks:
  #     - devnet
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   ports:
  #     - "5173:5173"

  # TODO: Build first and then deploy
  # backend:
  #   build:
  #     context: ./backend
  #     additional_contexts:
  #       fiql: ../fiql
  #   command: ["npm", "run", "dev"]
  #   volumes:
  #     - ./backend:/app
  #     - /app/node_modules
  #   networks:
  #     - devnet
  #   ports:
  #     - "3333:3333"
  #   env_file:
  #     - ./backend/.env
  #   depends_on:
  #     - db
  #     - redis

  db:
    image: postgres:18
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: app
    networks:
      - devnet
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    restart: always
    networks:
      - devnet
    ports:
      - "6379:6379"


networks:  
  devnet:
    driver: bridge